### ISSUE TITLE
[Request] Reduce reliance on JS

### ISSUE THREAD

**Issue by ghost** [nyaadevs/nyaa#137]
A separate template (front-end) for non JavaScript enabled users is much appreciated. At the moment, most things work great but the markup in descriptions is displayed raw and requires enabling current domain as well as Cloudflare scripts to resolve.

Keep up the excellent work!

P.S. The much-requested category tree/buttons would be a great companion to a static site.

**Comment by nyaadev** [comment]
JavaScript is an essential part of every modern browser. There is not even an option to disable it in the commonly used browsers, as far as I am aware.

While reducing JavaScript usage to a minimum is good for performance reasons, we will not switch to server side markdown rendering due to possible DoS exploits and the need for client side rendering for the preview.

If something else is completely broken without JavaScript you can let us know here, screenshots would be nice too.

**Comment by TheAMM** [comment]
Javascript is also used to create the quality/category filters.
![image](https://cloud.githubusercontent.com/assets/6820963/26251171/08cce9de-3cb5-11e7-9372-86b3b0a3b921.png)

**Comment by niiinii** [comment]
Thanks for the prompt explanation. It didn't occur to me that it is an avenue of exploit because previous/similar sites didn't require client JS markdown -- but if it keeps the site running then that's totally fine.

A little irrelevant but...
JavaScript can be disabled in major browsers (Chrome: in the dropdown site permissions from address bar; and Firefox: globally in an about:config flag) -- it's just not a very up-front option. Script-blocking browser addons/extensions have been around for over 10 years and has been popular with users that are tired of landing on annoying/malicious websites. Nowadays, many sites are designed well enough that people can get by without running scripts so I disallow all scripts until I find them truly necessary.

**Comment by ipatrol** [comment]
I would suggest a few bits of reading:
https://ponyfoo.com/articles/stop-breaking-the-web
https://www.leaseweb.com/labs/2013/07/10-very-good-reasons-to-stop-using-javascript/
https://nolanlawson.com/2016/10/13/progressive-enhancement-isnt-dead-but-it-smells-funny/

**Comment by Sapo84** [comment]
@ipatrol I would suggest not linking old articles like the second one (did you really read it in 2017 and found it worth linking to? And it was probably already clickbaity in 2013)  
The first one is a critique to client-side rendering frameworks(angular, ember, backbone, vue, react etc. etc.), nyaa.si has nothing of that sort and only uses javascript as enhancement (just as proposed in the page) so it does not apply (I also think it's slightly outdated since react, vue and angular2+ all have mature SSR implementations).  
The third one is similar to the first one so, again, it does not apply here, you can disable javascript and still be able to use the main nyaa functionality (downloading torrents).

If you wanted to prove your point you failed spectacularly.
