### ISSUE TITLE
502 Bad Gateway on creating a username outside the english alphabet

### ISSUE THREAD

**Issue by another-random-user** [nyaadevs/nyaa#197]
Tried creating a user name in Japanese and it showed me a 502 Bad Gateway error. Nothing about the alphanumeric stuff I got when I tried to create a username with a space in it. Also tried it in another alphabet and got the same.

**Comment by TheAMM** [comment]
The 502 sounds like a problem, but we're only allowing `a-zA-Z0-9_-` in our usernames.

**Comment by TheAMM** [comment]
Oh, right. For posterity, I fixed this in 081eb16246165ae97245ecd52f7476271e59b462 - the Unique check would query the DB, which would make MariaDB to try and lowercase the UTF username - since the column is ASCII only, exceptions occurred. Stopping the validation chain at the regex ensures the Unique check is not done.
