### ISSUE TITLE
Tracker issue

### ISSUE THREAD

**Issue by SnAFKe** [nyaadevs/nyaa#217]
I'm not sure if this error if owner of the site or is for the branch.

The problem is when you try to upload a torrent, the site owner put use their tracker so if we want to use a remote tracker we can't upload the torrent they force to use it their tracker, also the validation for the tracker is wrong, we need to use their tracker in the first line in the tracker information:

**Example:**

If we create a torrent with this information a tracker announce for the site is tracker1.com/announce

**Option 1**

tracker2.com/announce
tracker1.com/announce

**Option 2**

tracker1.com/announce
tracker2.com/announce

The option 1 not will work but if we use option 2 works. 

Practically force us to use our primary tracker as their tracker.

**What i want to archive**:

- Can use our remote tracker instead of theirs
- Check tracker validation in whatever line and not in first line.

**Comment by TheAMM** [comment]
Sorry, I'm not really sure what you're saying here?
We do not replace the trackers, [only verify that ours (the Nyaa.si tracker) is in the torrent](https://github.com/nyaadevs/nyaa/blob/master/nyaa/forms.py#L314-L333), either the announce list or as the primary tracker.

Or are you talking of another site?
It's easiest if you show me your .torrent (pop by the IRC or DM me on twitter or something), but we had someone with the same problem, and they were using `mktorrent` wrong (adding backup trackers instead of tracker tiers) so check your tool arguments, as well.

**Comment by SnAFKe** [comment]
Nobody say you replace the tracker if not force your tracker as primary.

I'll PM you in the IRC

**Comment by TheAMM** [comment]
We don't force our tracker to be the primary one either.
I'm fairly certain you're dumping all trackers into one tier, which means only the first one of them is going to be used (unless it fails so the next backup is used etc)

**Comment by TheAMM** [comment]
Confirmed on IRC, all trackers were being added as backup trackers.
