### ISSUE TITLE
nyaa tracker required to be listed first in torrent files

### ISSUE THREAD

**Issue by entitlement** [nyaadevs/nyaa#223]
Forgive me; I'm sure this is partially user error. I'm not a code-head and I don't make torrents very frequently.

I had an issue uploading a torrent, and was told that I didn't have the nyaa announce URL in my torrent, although it most certainly did, at least according to what qBT was telling me.

After snooping around in other torrents, I re-did the torrent, except listing the nyaa URL first this time (it wasn't before), and additionally giving it its own line/category by following it with an empty line per qBT's instructions. This time, it was listed as number/group 1, rather than 0 (zero) with the rest of the public trackers. Uploading this file worked fine, and I am seeding it now.

Allowing the nyaa announce URL to be in any position would make things simpler for uploaders.

On the other hand, if there's some technical reason it needs to be first, whether temporarily or indefinitely, it should at least be noted on the upload page. As of now, it just says the announce URL needs to be in the torrent, with no mention of order or priority.

If this is user error that I'm not aware of, please ignore.

Anyways, cheers on the new site. I'm sure lots of folks are glad to see it back in some form.

**Comment by TheAMM** [comment]
The tracker is allowed to be in any tier - what you had done was add all trackers into the same tier which meant only the first one of them would be used, the rest only if the first one fails.

The nyaa tracker technically *was* in the torrent (and we would be able to find it if we wanted to -) but it was useless. Since our stats are currently tied to our tracker (and since we're not just an index) we oh-so-horribly require that people add our tracker to the torrent. Doesn't have to be first, but it has to *work* and not be a backup.

The proper way to add trackers in most(?) GUI tools is to group the tiers ala
```
http://tracker1.tier1:port/announce
http://tracker2.tier1:port/announce

http://tracker1.tier2:port/announce
http://tracker2.tier2:port/announce
```

*I blame the torrent clients for failing to explain how tracker tiers work!*
You're the second one to fall for this today (third in total that I know of), so seems like we have to add some logic to warn usersand tell them how to do it properly (or possibly do it for them, as I wrote a Javascript bdecoder and torrent metadata parser earlier).
