### ISSUE TITLE
search not found

### ISSUE THREAD

**Issue by mgyver** [nyaadevs/nyaa#227]
entering "ovg 057", returns 1 result of "OVG-057", while
entering "ovg 57", returns no result.

the same case happening when
entering "heyzo 0569", returns 5 results of "HEYZO 0569", while
entering "heyzo 569", returns no result.

would you please improve the search for this case.

**Comment by Mause** [comment]
Does "ovg *57" work?

**Comment by TheAMM** [comment]
The simple string query syntax only allows wildcards after the token, not before.
This can (probably) be fixed with a filter in the ES analyzer:
```yaml
trimZero:
    type: pattern_capture
    patterns: 0*([0-9]*)
```
to get rid of leading zeroes. Wonder if that'd break anything...

**Comment by mgyver** [comment]
also : 
> entering "hd juy" returns results of the "[HD] JUY-*** "; while optimum results should include the "[FHD] JUY-*** "
> entering "dandy 12" returns results of the "DANDY-12*" or "DANDY *** 2013/12/19"; while optimum results should include the "DANDY-412 *** ", "DANDY-512 *** " and "DANDY-*12 *** ".

**Comment by TheAMM** [comment]
The simple string query syntax only looks for prefixes matching the token in the index, not suffixes.
`hd` will not match `fhd`, and `12` will not match `412`.
Use the tools you are given: `hd|fhd juy`. For the latter I can't give a catch-all, since like I said before, no prefixed wildcards in the simple string query syntax.

**Comment by aldacron** [comment]
@mgyver feel free to open another issue for that
