### ISSUE TITLE
Discourage non-embed image links in description

### ISSUE THREAD

**Issue by Kuraperunat** [nyaadevs/nyaa#236]
There's a growing trend of uploaders only putting in a link to the description that only says e.g. "SCREENSHOT", which then leads to a random ad-ridden cashgrab image hosting site. These people should be encouraged to use embed images instead.

Encouraging all embed images would be trivial to exploit, so the solution is likely to discourage these ad links somehow, e.g. by coloring the torrent with a red color just like re-encodes and such are. In practice this would require making a filter that colors the torrent red if the description contains these links and/or any url shotener links.

**Comment by CounterPillow** [comment]
Alternatively we could just disallow certain URLs like old nyaa did, and tell uploaders to choose one of a few endorsed image hosts.

**Comment by snowfag** [comment]
We're not trying to fix stupidity.

**Comment by aldacron** [comment]
This is actually a valid suggestion.

**Comment by Arylide** [comment]
This is hard to do without effectively killing off JAV uploads, since they are the main ones doing this sort of thing. They make money of sorts off of those crappy image sites, there isn't much we can really do without scaring them off. I was considering some sort of warning for known crap hosts in descriptions, but that may be difficult to maintain. So unless you are going to submit a PR for this, we will need to table this until we aren't working on more core things.
