### ISSUE TITLE
How about making top navbar sticky while browsing the page?

### ISSUE THREAD

**Issue by xmhscratch** [nyaadevs/nyaa#274]

**Comment by sharkykh** [comment]
The alternative could be adding a :top: button.

**Comment by CounterPillow** [comment]
@sharkykh or just have people learn about the key on their keyboard labelled "Home".

**Comment by xmhscratch** [comment]
The sticky behaviour could be like this one [https://semantic-ui.com/examples/sticky.html](url) for faster searching and navigation.

**Comment by TheAMM** [comment]
Mmm, the example might be neat but someone would have to implement it, and make sure it doesn't break anything (eg. the droplist, the mobile layout, etc)

**Comment by sharkykh** [comment]
@TheAMM Bootstrap has this built-in

**Comment by sharkykh** [comment]
@CounterPillow 
May I ask why are you against it? It's not like it takes a huge chunk of the view...

**Comment by CounterPillow** [comment]
@sharkykh I generally don't like the page navigation obscuring things as I scroll down, especially since if I need it, scrolling back up is quick and easy and I'll have to move my mouse or use my keyboard anyway to use the navigation. I usually prefer websites to act like pages, and when you add sticky things to them it sort of breaks the assumption that "scroll" means "scroll over the page". The scrollbar loses its meaning, as the page is no longer one coherent thing.

This is totally a subjective thing of course, but for example Twitch makes heavy use of sticky navigation bars and it makes me want to vomit, since I'm boxed in between 60 px of topbar, 60px of sidebar, 60px of bottom bar and 340 px of chat bar. If you scroll on that page, it actually becomes really hard to focus on the content you're scrolling over, because there's so much shit sticking to the view.

nyaa.si just has a top navigation bar (for now), and making that sticky would essentially mean to see 2 less torrents at once. When the inevitable happens and somebody requests the page navigation to also be sticky, that'll increase to 3 or 4.

So since my complaints are fairly vague and boil down to "I don't like it and I think it's bad design language", I am mostly arguing for this being configurable rather than forced. More complexity, but I will have less nightmares of being chased by navbars.

**Comment by sharkykh** [comment]
> [...]
> nyaa.si just has a top navigation bar (for now), and making that sticky would essentially mean to see 2 less torrents at once. When the inevitable happens and somebody requests the page navigation to also be sticky, that'll increase to 3 or 4.

Twitch is an extreme example, as they _are_ overdoing it.
Nonetheless, that is a good point:

> I am mostly arguing for this being configurable rather than forced. More complexity, but I will have less nightmares of being chased by navbars.

I agree with you. Having this user-configurable would be best.
For the time being, if we do this, the state can be stored just like Dark Mode (using [Local Storage](https://www.w3schools.com/html/html5_webstorage.asp))

> EDIT: Also, when I resize my browser window to half the width of my screen (which is how I usually do my web browsing), I get the shitty hamburger menu top bar, and with the hamburger activated to have the search options and such open, making it sticky would actually use up around half of the entire screen space no matter how much you scroll, which is an insane waste of space.

I don't see a reason to scroll the page with the navigation dropdown open, as the reason you open the navbar is to navigate to a different page / perform a search.

BTW regarding that menu, making the navbar "sticky" does introduce a different issue (missing background):
![image](https://user-images.githubusercontent.com/10238474/27764777-a095e146-5eaa-11e7-81ac-82c43dd4a699.png)

I think that's due to the filter dropdowns being generated by bootstrap-select after the page loads.

**Comment by S-ed** [comment]
```css
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document regexp("^https?:\/\/(?:www\.)?nyaa\.si\/.*") {
    .navbar {
        top: 0;
        position: fixed;
        width: 100%;
    }
    
    body > .container {
        margin-top: 70px;
    }
}
```
Install Stylish, add this style.
Tested, no background missing.

**Comment by CounterPillow** [comment]
@S-ed use Stylus instead of Stylish, Stylish tracks your web browsing activity for marketing purposes.

**Comment by S-ed** [comment]
@CounterPillow Stylus is a web extension, it could not inject CSS to Firefox GUI. And I'm using Stylish mainly for that.
Also, it's ugly...

**Comment by Arylide** [comment]
https://github.com/nyaadevs/nyaa/pull/575#issuecomment-505566727
