### ISSUE TITLE
Add a Anime Dub section & Total Torrent DL

### ISSUE THREAD

**Issue by RepoBike** [nyaadevs/nyaa#333]
Since there is alot of Dubbed Anime on the site. I would like to see a section for Anime Dub with a Anime-Dub icon.

Also show how many times the Torrent itself has been downloaded. Not just how many times the file has been completed.

Maybe a way to weed out any Trolls. haha :)

**Comment by TheAMM** [comment]
Dubbed means English-translated. Splitting uploads into more and more sections is just complicating things.
We'll eventually add metadata tags for uploads, as in languages and most importantly a field for `mediainfo`.

The download statistic states how many torrent clients have finished downloading the entire torrent, as reported by the tracker. It's a realer value than the `.torrent` download count because of magnet links.
I don't know what you mean by trolls.

**Comment by RepoBike** [comment]
> Dubbed means English-translated. Splitting uploads into more and more sections is just complicating things.
We'll eventually add metadata tags for uploads, as in languages and most importantly a field for mediainfo.

Iv seen some comments on torrents Saying why does this have a Anime-sub icon when its dubbed. So thats why i posted this question.
