### ISSUE TITLE
Setting language(s) and tags on upload

### ISSUE THREAD

**Issue by TakingItCasual** [nyaadevs/nyaa#388]
The 4chan nyaa has the option to set languages and tags (such as video quality), which can be seen from [here](https://nyaa.pantsu.cat/upload). A torrent's language(s) can then be seen on the torrent's page, and as a flag over its category. Video quality is also seen on the torrent's page. There's various database ID tags as well, but I thought language and video quality would be nice tags to have for nyaa. (Bluray seems to be only 1 option, but 720p BDs are quite common so that could be added.)

**Comment by CounterPillow** [comment]
There are plans to have a mediainfo output field for uploaders to copypaste into which could parse all of these things.

I think having people manually tag releases wouldn't be that useful, since most of them would be left insufficiently tagged (as this is a public tracker). Tags are most useful for searching which is not that useful when only a minority of the torrents have any tags to begin with.

**Comment by Arylide** [comment]
As was already said, there is very little point to implementing it on a voluntary basis as you'll just end up with some things not having it.
