### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by moi15moi** [nyaadevs/nyaa#422]
Hi,

Can we have access to bbcode for the prez ? The markdown does not have all the option.

Thank you :)

**Comment by moi15moi** [comment]
Oups, I'm sorry I am not in the good category. How can we change the cateagory of our topic ?

**Comment by TheAMM** [comment]
What?
There is no bbcode on the site.

**Comment by CounterPillow** [comment]
>The markdown does not have all the option.

What option are you missing?

**Comment by moi15moi** [comment]
I miss

1. To underline
2. Center the text
3. highlight
4. Font size

**Comment by CounterPillow** [comment]
>To underline

fair

>Center the text

doesn't seem like something a description would need to do, you're not doing a layout for a magazine here

>Highlight

Do you mean setting background or foreground colour? Again, I don't see the use for this, if you want to emphasise something, use **bold** or ***bold italic***

>Font size

No. Markdown doesn't work by having you explicitly choose the way something is rendered, only the semantics of the document you're laying out. This is so that our stylesheet and future adjustments to it are what defines the look. If you want to use a heading, use the markdown for declaring a heading. The font size should be up to the website. If the description you're trying to make is not logically grouped into headings, paragraphs, lists and tables, the problem isn't that you can't set an explicit font size; it's that your description isn't human-readable to begin with.

Most of these complaints seem like you want to write awful 2000s eras forum posts with 90pt red centred text, and I for one am glad we do not support this (ab)use.

**Comment by moi15moi** [comment]
Ok

This is a prez with the bbcode : https://ww1.yggtorrent.com/torrent/filmvid%C3%A9o/animation-s%C3%A9rie/134284-miracle_sharingan_fansub_dragon_ball_super_%C3%89pisode_117_vostfr_version_pro_studio1080pac-3

It's very clean


But, the best I can do with the markdown it's that : https://nyaa.si/view/986034

Do you see the difference ?

Also, it's easier to write in bbcode (But that's for me)

**Comment by TheAMM** [comment]
Read the [Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (and *please* don't use url shorteners).
You can make your description look nicer by using `# Headings` and possibly even tables.
Sure, bbcode allows you to design more, but we are not a forum. Constraining people to the same standards will, like Pillow said, keep the general look clean. For example, users on the default theme setting custom colors would look bad on dark mode and vice-versa. The description doesn't have to be that visually grand.

However. Underlining (`<ins>`) and possibly hilighting (`<mark>`) can be added.

**Comment by CounterPillow** [comment]
>This is a prez with the bbcode

absolute cancer, glad we don't support this.

**Comment by moi15moi** [comment]
@CounterPillow : Why you don't like it ?

**Comment by CounterPillow** [comment]
@moi15moi 

The centreing is dumb. In Latin scripts, we read left to right, and if each line starts at a different horizontal offset, your eyes are trying to find the start of each line individually. Plus, in your lists of properties, it means none of them line up at all. Your use of it actually makes your description harder to read.

The red huge text is dumb. Why would you make the title red? It just adds more visual noise. If you didn't have every part of your description be that cluttered with useless graphics for titles and emboldening and italics everywhere, you wouldn't need big red text for emphasis.

**Comment by moi15moi** [comment]
Ok, thanks for your argument but it would be better if nyaa as his own markdown editor.

**Comment by alexbevi** [comment]
@moi15moi @CounterPillow @TheAMM do you think having a toolbar might help the user (something along the lines of https://github.com/nikolas/markdown-toolbar)

**Comment by TheAMM** [comment]
Markdown is meant to be simple to read and therefore easy to remember; it's almost completely intuitive. Well, *almost*. Tables are the hardest thing you can do in Markdown, and if you know you want tables you'll probably be looking it up already.
A toolbar might be nice, but also unnecessary because of the above; we're not really losing anything if users don't click the `Markdown supported` link to find out what they can do - they'll just write their description or comment in plain text.
Do I think it might help the user? Yes. There are... all sorts.
But do we need it? My opinion is no, at least for now, and especially for using a jquery plugin.

**Comment by TheAMM** [comment]
Still tied to #423.
