### ISSUE TITLE
Category Representation

### ISSUE THREAD

**Issue by SiIky** [nyaadevs/nyaa#429]
# What

I wanna propose a new way to represent the categories (`c`) on the query string (QS). It's more flexible and (I think) may be easier to implement.

# Why

I'd like to select more than one category at a time.
This is not possible right now, unless you would allow for `c` to appear more than once on the QS, but that is not such a good idea because it makes processing the QS a lot more complex.

# How

Currently there are 6 categories and 17 sub-categories in total.

```txt
 1. Anime
     1. Anime Music Video
     2. English-translated
     3. Non-English-translated
     4. Raw
 2. Audio
     1. Lossless
     2. Lossy
 3. Literature
     1. English-translated
     2. Non-English-translated
     3. Raw
 4. Live Action
     1. English-translated
     2. Idol/Promotional Video
     3. Non-English-translated
     4. Raw
 5. Pictures
     1. Graphics
     2. Photos
 6. Software
     1. Applications
     2. Games
```

I propose using a bitmap, where each bit represents a sub-category, `1` means "search for it" and `0` means "do not search for it".
Each category is the collection of all of its sub-categories, so there's no need to add a bit for categories, only sub-categories. This means a category selection is a number with at least 17 bits. Doesn't matter whether it's signed or unsigned, for now, but unsigned makes some things easier.

```c
#define NBITON(N) (1 << N)

enum categories {
    CAT_ANI_AMV       = NBITON(0),
    CAT_ANI_EN        = NBITON(1),
    CAT_ANI_NEN       = NBITON(2),
    CAT_ANI_RAW       = NBITON(3),
    CAT_ANI           = CAT_ANI_AMV | CAT_ANI_EN | CAT_ANI_NEN | CAT_ANI_RAW,

    CAT_AU_LOSSLESS   = NBITON(4),
    CAT_AU_LOSSY      = NBITON(5),
    CAT_AU            = CAT_AU_LOSSLESS | CAT_AU_LOSSY,

    CAT_LIT_EN        = NBITON(6),
    CAT_LIT_NEN       = NBITON(7),
    CAT_LIT_RAW       = NBITON(8),
    CAT_LIT           = CAT_LIT_EN  | CAT_LIT_NEN | CAT_LIT_RAW,

    CAT_LACT_EN       = NBITON(9),
    CAT_LACT_IPV      = NBITON(10),
    CAT_LACT_NEN      = NBITON(11),
    CAT_LACT_RAW      = NBITON(12),
    CAT_LACT          = CAT_LACT_EN | CAT_LACT_IPV | CAT_LACT_NEN | CAT_LACT_RAW,

    CAT_PICS_GRAPHICS = NBITON(13),
    CAT_PICS_PHOTOS   = NBITON(14),
    CAT_PICS          = CAT_PICS_GRAPHICS | CAT_PICS_PHOTOS,

    CAT_SW_APPS       = NBITON(15),
    CAT_SW_GAMES      = NBITON(16),
    CAT_SW            = CAT_SW_APPS | CAT_SW_GAMES,

    /* has to be updated when categories are added or removed */
    CAT_INVALID       = NBITON(17),
};
```

With this, selecting, for example, the categories

```txt
 1. Anime
     2. English-translated (bit 1)
     4. Raw                (bit 3)
 3. Literature
     1. English-translated (bit 6)
     3. Raw                (bit 8)
```

would give the number `330` (`101001010` in binary).

There's nothing special to say about reading/writing from/to the QS, using the same representation is enough. Here is also one of the places where using an unsigned number is easier.

# Limitations, Safeguards and Defaults

## Limitations

Does not support sub-sub-catgories and beyond. These do not exist at the moment, so it's not a problem.
If having sub-sub-catgories is a possibility in the future, then the whole scheme should be changed to minimize future work.

## Safeguards

To test whether a number is a valid category selection or not, just compare with `CAT_INVALID`:

```c
/* if `ucats` unsigned */
bool uval = ucats < CAT_INVALID;

/* if `scats` signed */
bool sval = scats >= 0 && scats < CAT_INVALID;
```

## Defaults

The value for searching `All categories`, i.e., no categories selected, could be `0`, similar to how it works now.

In case a number is not a valid selection (see above), it should default to `All categories`.
This is also a problem on the current scheme: When the string given to `c` is not `number_number`, for example, `0_c`, the server sends back a "Bad Request" message. A better thing to do would be to default to `All categories`.

# Some example code

```c
/* add the enum definition above and compile with `cc -o nyaa` */
#include <stdio.h>
const char * cat2str (unsigned int cats)
{
    static const char strs[CAT_INVALID + 1][18] = {
        [CAT_ANI_AMV]       =  "CAT_ANI_AMV",
        [CAT_ANI_EN]        =  "CAT_ANI_EN",
        [CAT_ANI_NEN]       =  "CAT_ANI_NEN",
        [CAT_ANI_RAW]       =  "CAT_ANI_RAW",
        [CAT_AU_LOSSLESS]   =  "CAT_AU_LOSSLESS",
        [CAT_AU_LOSSY]      =  "CAT_AU_LOSSY",
        [CAT_LIT_EN]        =  "CAT_LIT_EN",
        [CAT_LIT_NEN]       =  "CAT_LIT_NEN",
        [CAT_LIT_RAW]       =  "CAT_LIT_RAW",
        [CAT_LACT_EN]       =  "CAT_LACT_EN",
        [CAT_LACT_IPV]      =  "CAT_LACT_IPV",
        [CAT_LACT_NEN]      =  "CAT_LACT_NEN",
        [CAT_LACT_RAW]      =  "CAT_LACT_RAW",
        [CAT_PICS_GRAPHICS] =  "CAT_PICS_GRAPHICS",
        [CAT_PICS_PHOTOS]   =  "CAT_PICS_PHOTOS",
        [CAT_SW_APPS]       =  "CAT_SW_APPS",
        [CAT_SW_GAMES]      =  "CAT_SW_GAMES",
        [CAT_ANI]           =  "CAT_ANI",
        [CAT_AU]            =  "CAT_AU",
        [CAT_LIT]           =  "CAT_LIT",
        [CAT_LACT]          =  "CAT_LACT",
        [CAT_PICS]          =  "CAT_PICS",
        [CAT_SW]            =  "CAT_SW",
        [CAT_INVALID]       =  "CAT_INVALID",
    };
    return (cats <= CAT_INVALID) ?
        strs[cats] :
        "(null)" ;
}

/* Print a given category selection as a series of bitwise OR operations */
void print_cats (unsigned int cats)
{
    unsigned int f = 0;
    while (!(cats & NBITON(f)))
        f++;
    printf("%s", cat2str(NBITON(f)));

    for (unsigned int i = f + 1; i < 17; i++) {
        unsigned int bit = NBITON(i);
        if (cats & bit)
            printf(" | %s", cat2str(bit));
    }
}

int main (void)
{
    /* Print a table similar to the enum definition */
    for (unsigned int i = 0; i < 17; i++) {
        unsigned int bit = NBITON(i);
        printf("%s\t= %u\n", cat2str(bit), bit);
    }

    unsigned int cats = CAT_ANI_EN | CAT_ANI_RAW | CAT_LIT_EN | CAT_LIT_RAW;
    print_cats(cats);
    printf(" = %u\n", cats);

    return 0;
}
```

# Conclusion/Acknowledgments

I'm not familiar at all with the codebase or Python, and I don't even know how/if it could be easily done in Python. It'd be great if someone could enlighten me or give me pointers on where to look, to get an idea of where things will have to change.
Everything here is open for discussion, I'd like comments and/or suggestions.

**Comment by TheAMM** [comment]
Aw man, this is terribly well put together. I wish all issues and PRs were this neat. Kudos.

I think bitmaps are damn neat. We already kinda [use them](https://github.com/nyaadevs/nyaa/blob/master/nyaa/models.py#L69-L101) on the DB side for a some of [the torrent flags](https://github.com/nyaadevs/nyaa/blob/master/nyaa/models.py#L251-L257), although the downside of this is that [the queries have to unmap the flags](https://github.com/nyaadevs/nyaa/blob/master/nyaa/search.py#L359-L360), which convolutes them and may? affect performance. Python can do bitwise operations and such, don't worry.

Anyhow, starting with:
> I'd like to select more than one category at a time.

The main reason the search is currently lacking (no filtering like date/age, size, no multiple categories or excluding categories) is that webdesign is a *paaain* - none of the active or half-active or even nigh-dead developers have a... good enough relationship with webdesign that they'd go *Hey, I'll just rewrite the search UI without making it look terrible, easy!* Backend is not a problem, backend everiday, but taking the dive into the horrible mix of HTML and CSS is.

> sub-sub-categories

The current category system doesn't support these either; we used to have a plain Category-class which could simply have another Category as the parent, but due to reasons which I forget (simplicity? Nyaa.se similarity? Performance??) we went with the main/sub category combo.

> In case a number is not a valid selection (see above), it should default to `All categories`.

The `Bad request` is a bit scary, true, that should be fixed. However, I don't consider implicitly defaulting to all categories a good choice. Perhaps if accompanied by a warning box about an invalid category.

And now for the main proposal:
> It's more flexible [...]

Bitmaps and bitmasks and the like are damn neat, but they're far from human-friendly.
My concerns are:
  * The amount of categories is "limited" - Python can automatically handle big numbers and MySQL does have `BIGINT` with 8 bytes (or in this case, 64 bits/categories), but there is a limit. Category ids are technically limited as well, but even just two bytes will bring us to a signed 32767 cap. Bitmaps? Restricted.
  * The categories are not human-friendly. Disregarding people making scrapers or clients or apps for the site, a single number will be a black box for those not checking out the source - people can't modify their RSS by simply swapping or adding a category. Useful in some cases, but not here.
    * The example of combining several categories into `330` was neat; it looks fine, a small-ish number. But say we have 20 categories and search for the one marked 20 - that's `1048576` - scary! Why is there a big number like that? Obfuscated.
  * Adding and removing categories... works, yes. There's no need to have relevant subcategories be nearby bits; a new category to Anime could just be bit 17, and removing a Live Action would leave a slot open - but as bits are limited, reuse could be problematic and out-of-order bits for related categories, while not serious, is a useless drawback no gain. Messy.
  * It convolutes the category parsing. We do currently have to process the category strings (split them and grab a matching category by the ids), but extracting bits out of a number is a bit too low-level for a web app parsing `GET`s. Unnecessary.

> [...] and (I think) may be easier to implement.
> This is not possible right now, unless you would allow for `c` to appear more than once on the QS, but that is not such a good idea because it makes processing the QS a lot more complex.

I really appreciate the effort that went into thinking out the idea, creating the examples and everything, but parsing multiple parameters out of a `GET` request is not a problem at all. Now, in hindsight, it's slightly humorous how you grant that you don't know anything about the existing code or Python, but have fears about parsing query strings getting complicated.

In Flask (which is using Werkzeug), it's as easy as `flask.request.params.getlist('c')` to get all categories given in `?c=1_0&c=2_0&c=...`. The `request.params` (`GET`) and `request.form` (`POST`) are using Werkzeug's `MultiDict`, and we can get all repeated parameters with [`.getlist()`](http://werkzeug.pocoo.org/docs/0.14/datastructures/#werkzeug.datastructures.MultiDict.getlist).

Even if Flask was unable to parse the repeats, I'd much rather do custom parsing in the form of `c=1_0+2_0` to search for two categories and for example `ec=3_0+5_0` to exclude categories. This would Javascript, though, breaking non-JS clients (although already somewhat broken), and would slightly complicate making programmatic `GET`s because of the custom parameter logic (as in, not just a toggle, but a structured value) - but nowhere near the level of requiring people to do operations on bits (...summing numbers, but still).

(The repeated parameters shouldn't be a problem to generate either on the scripting side; Python's `requests` is easy to use for a `GET` with repeated parameters - `requests.get(url, params={'c' : ['1_0', '2_0']})`)

----

So, in closing. Thanks for your effort, it was a fine post to read.
However, while a neat idea, this tries to solve something that is already very simple to solve, and the neatness doesn't justify the drawbacks. So I'll have to reject this proposal, and as the slot for the "search categories issue" is filled by #27, closed we get.

I once saw someone being told "*Why didn't you ask us first if we even wanted this before offering a PR for it?*" - I thought it rude, but in this instance, I wish I could've saved you this effort by answering a quick question about parsing multiple `GET` parameters in Python (Flask).
