### ISSUE TITLE
Feature Request: Add a change Date Format 

### ISSUE THREAD

**Issue by tlzydude** [nyaadevs/nyaa#568]
Can you please add a option to change the Date format in Date from yyyy-mm-dd                           https://snag.gy/mbvMSa.jpg to dd-mm-yyyy. It is very confusing for those who are not use to this type of format to read backwards.

**Comment by nyaadev** [comment]
very confusing

**Comment by CounterPillow** [comment]
I can see this being something we can easily do in JS, no need to close.

**Comment by Arylide** [comment]
I wouldn't merge it anyway, just learn to adapt to the global ISO standard.

**Comment by CounterPillow** [comment]
reeeeeeee

**Comment by tlzydude** [comment]
the suggestion was a simple button above Date for a user to click and pick a format they want, but if it's such a hassle then it's OK ISO will have to do thank you for the reply

**Comment by Arylide** [comment]
It really isn't about it being a hassle if you read my reply, it is about fairness. This software is meant to accommodate people in the most international way we reasonably can. That is why only English is supported as of now for the user interface, we want to keep things simple and international standards friendly. If we were going to accommodate everyone we'd probably need to start with language rather than date formats. You're in fact the first person in two years that thought the date was enough of a difficulty to deal with to make an issue about it. I don't even think you're wrong, I just believe that supporting international standards is a meaningful hill to die on.
