### ISSUE TITLE
Forced mobile version for iPad 

### ISSUE THREAD

**Issue by salimos** [nyaadevs/nyaa#599]
The website on safari mobile for iPad force the mobile version without no option to go the the desktop version) which can handle perfectly the desktop experience

**Comment by ReimuHakurei** [comment]
There is, unfortunately, no way to target cell phones without also targeting your iPad (at least, not without a large amount of effort, which due to the tiny percentage of users on mobile devices of any sort is not worth our time to do).

We force a viewport width of 480px on all mobile devices in order to make the website usable on smartphones, with the unfortunate side-effect of making the website less usable on tablets such as your iPad.

As far as I am aware, there aren't any torrent clients on the iOS App Store, while there are a great number of them on the Google Play Store for Android devices. As most people using a tablet of any sort are probably using an iPad, while people using a smartphone are about equally to be using iOS or Android, and thus most of the mobile users of the website are going to be browsing on smartphones, we made the active decision to prioritize usability for smartphones at the expense of tablets.

I know Firefox for Android has a "Request desktop site" option which ignores this viewport directive, which has the function of displaying as it would on a desktop. Is there not a similar function on Mobile Safari?

**Comment by nathanielcwm** [comment]
I used to ba able to use the desktop version of nyaa on safari. Ever since iOS 13 it won't allow me to switch to the desktop site even when using desktop mode.

My Useragent:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
