### ISSUE TITLE
Please add &limit OR &count to RSS query string

### ISSUE THREAD

**Issue by Kamushek54** [nyaadevs/nyaa#604]
Hi!
Example: /?page=rss&q=Somali&c=1_0&f=0&count=10
it's must returned 10 results for me.

**Comment by ReimuHakurei** [comment]
No.

The intended purpose of the RSS feed is so that new releases can be automatically downloaded by your BitTorrent client. 

Because the RSS pages are refreshed very frequently by said torrent clients, the page is intentionally given very limited functionality, to maximize performance and reduce the load it puts on our server. 

If we started adding more features to it, the load the RSS page puts on our server would be substantially higher. For this reason, no new functionality is going to be added to the RSS feed anytime soon.
