### ISSUE TITLE
When Desktop Mode is enabled on iPadOS 13.5 mobile website is shown.

### ISSUE THREAD

**Issue by nathanielcwm** [nyaadevs/nyaa#617]
User Agent:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

Expected Behavior:

When switched to desktop mode desktop site is shown

Actual Behavior:

Mobile Site is shown.

**Comment by nathanielcwm** [comment]
Happens on the current commit on nyaa.si of https://github.com/nyaadevs/nyaa/tree/97c32a483f2e5c553b8a01e147d441b06b48a195

**Comment by ReimuHakurei** [comment]
When in "Desktop" mode, iPads still honor the meta viewport flag, while real desktop browsers do not. The viewport flag is set to make the site actually usable on cell phones.

There is no way for us to fix this on your iPad without us breaking cell phones in the process. The problem is that iOS does not actually act like a desktop browser when in "desktop" mode.
