### ISSUE TITLE
Search queries using | with multiple words

### ISSUE THREAD

**Issue by Zarnaik** [nyaadevs/nyaa#8]
Hi

Currently the or-operator is working, when used for a single word, e.g. random|word will match both of the terms. When using multiple words though, it doesn't work, e.g. "two words"|"some other search" (this is how it used to work on nyaa.se)

I don't know if this is because the quoted searches aren't yet implemented, or this specific case hasn't been accounted for with the piping. Or perhaps has the syntax for such searches changed?

Kind regards.
Also, thanks a lot for creating this alternative.

**Comment by TheAMM** [comment]
The search is currently using MySQL FULLTEXT search: https://dev.mysql.com/doc/refman/5.7/en/fulltext-natural-language.html 
There are no special operators; the | does nothing.

We're working on a better search and checking if Elasticsearch beats Sphinx (which Nyaa was using, but is a bit more troublesome to set up, but then again ES this and Sphinx that and-).
Don't worry about search, it's shit and thanks to our frantic development, nobody realized how shit it actually was. But we do have our top guys on it right now. Top guys. We'll get that *K-On!* soon.

**Comment by uMag** [comment]
@TheAMM I have used sphinx + postgresql and elasticsearch + postgresql on large social network, I'm sticking to usage of ES it's just faster and simplier to maintain than sphinx

**Comment by TheAMM** [comment]
We figured that as well, thanks for the heads up @uMag.

**Comment by reconman** [comment]
Not related to wildcards but I've found a problem with the search. If you search for "Ghost in the Shell" it will return 0 results.

https://nyaa.si/?q=Ghost+in+the+Shell&f=0&c=0_0

Searching for "Arise", however, returns a few dozen results with "Ghost in the Shell" in the title.

https://nyaa.si/?q=Arise&f=0&c=0_0

It can't be because of the space because "Danshi Nichijou" returns results. I have no idea what the source of the problem is.

**Comment by TheAMM** [comment]
@reconman: forget everything about current search. It's barely functional, we're aware of it, it will be completely replaced and all reports regarding the current search will be moot.
